#!/usr/bin/php -q
<?php

require_once 'vendor/autoload.php';

use Simples\Kernel\App;

unset($argv[0]);
$service = $argv;

if (empty($service)) {
    $service = ['help'];
}

$app = new App(['root' => __DIR__]);

$app->cli($service);